env:
  browser: true
  es2021: true
  jest: true
extends:
  - plugin:react/recommended
  - standard
settings:
  react:
    version:
      detect
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules: 
  camelcase:
   - off
  jsx-quotes:
    - error
    - prefer-double
  quotes:
    - error
    - double
  react/prop-types:
    - off
  react/react-in-jsx-scope:
    - off
  no-unused-vars:
    - off